import "react-perfect-scrollbar/dist/css/styles.css";
// import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../public/assets/css/style.css";
import "../public/assets/css/widgets.css";
import "../public/assets/css/responsive.css";
import ScrollProgress from "../components/elements/ScrollProgress";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Stories - Personal Blog HTML Template",
  description: "Generated by Stories - Personal Blog HTML Template",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={notoSansJP.className}>
        <ScrollProgress />
        {children}
      </body>
    </html>
  );
}
